name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for full analysis

      - name: SonarQube scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Uncomment to fail the build if the SonarQube Quality Gate fails
      # - name: Check SonarQube Quality Gate
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
            gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | \
            sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y
          trivy fs .

      - name: Docker build and push
        run: |
          docker build --build-arg TMDB_V3_API_KEY=9148c23062dfce8824e0e2a10b1b2636 -t netflix .
          docker tag netflix elviedjomo/netflix:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push elviedjomo/netflix:latest
        env:
          DOCKER_CLI_ACI: 1

  deploy:
    name: Deploy to AWS EC2
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Pull Docker image
        run: docker pull elviedjomo/netflix:latest

      - name: Trivy image scan
        run: trivy image elviedjomo/netflix:latest

      - name: Run container
        run: docker run -d --name netflix -p 8081:80 elviedjomo/netflix:latest
